# Generated by Django 3.2.8 on 2021-10-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimetsu_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raca',
            name='descricao',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
