# Generated by Django 3.2.8 on 2021-10-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimetsu_app', '0002_raca_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagem',
            name='peso',
            field=models.FloatField(help_text='Peso em kilos'),
        ),
    ]
